### ISSUE TITLE
[Proxy Cache Purge - 5.1.3] - varnish-http-purge.php file - line 434 - Typo? 

### ISSUE THREAD

**Issue by florian-digital-tree-company** [Ipstenu/varnish-http-purge#100]
Hi there,

When trying to understand its code for learning purposes, I noticed something that might be a typo in the 'varnish-http-purge.php' file at line 434: 'dectivate' instead of 'deactivate'. I'm not competent to judge the impact, if any:

![image](https://user-images.githubusercontent.com/130935186/232342952-52dd9e31-e0fc-4e0d-ab9a-a68b19b2add5.png)

**Comment by Ipstenu** [comment]
That would be a typo, yep. Fixed in the next version.
