### ISSUE TITLE
Not purging the wp-api urls for retrieving posts

### ISSUE THREAD

**Issue by kala725** [Ipstenu/varnish-http-purge#15]
Not purging the wp-api urls for retrieving posts

**Comment by Ipstenu** [comment]
Sorry, can you be a little more explicit?

What wp-api URLs? You mean in 4.4 with the json api installed? If so, can you give me an example of what the URLs are you're trying to access?

**Comment by Ipstenu** [comment]
No reply in nearly 3 months. If you can come back with more info, I'll revisit.
