### ISSUE TITLE
Empty Cache

### ISSUE THREAD

**Issue by phh** [Ipstenu/varnish-http-purge#31]
Hi there!

The latest update of the plugin changed the "Purge Varnish" button to instead "Empty Cache" which I agree in some sense is more user friendly.

But in reality it's not really "true".

Sometimes when you're using a persistent cache this has to be flushed aswell to "flush the cache". Unless VHP started doing this is it not really an "Empty Cache". In reality it's really flushing Varnish only (or emptying the frontend cache).

Changing this to "Empty Varnish Cache" would be more precise.

**Comment by Ipstenu** [comment]
This is a matter of English sucking and having limited space.Its no more or less true than the myriad plugins that also say 'empty cache' when they're only talking about their one cache, and yes, they all have naming clashes. This is not perfect, and my concern was "Purge Varnish Cache" tested as too long on the admin toolbar.

**Comment by phh** [comment]
Makes sense. Thank you.
