### ISSUE TITLE
`wp varnish purge https://example.org` doesn't work

### ISSUE THREAD

**Issue by ocean90** [Ipstenu/varnish-http-purge#35]
Since acfe0b0deaac4bdb78f742ef7f5c8c7e4b609a19 the URL gets the home URL prefixed: `$url = $this->varnish_purge->the_home_url() . esc_url( $url );` . That doesn't seem right.

**Comment by Ipstenu** [comment]
What's it outputting for you? Does `wp varnish purge https://example.org/` work? (with the trailing slash)

**Comment by ocean90** [comment]
@Ipstenu The output is always `The Varnish cache was purged.` so that's not helpful. 😏

It's not about the trailing slash: `$url = $this->varnish_purge->the_home_url() . esc_url( $url );` produces `https://thehomeurl.comhttps://example.org/`.
