### ISSUE TITLE
Revert the green background color for the "Empty Cache" toolbar item

### ISSUE THREAD

**Issue by ocean90** [Ipstenu/varnish-http-purge#42]
Since the last update the "Empty Cache" item has a green background color `#46B450`. But it actually means nothing as it's hardcoded in https://github.com/Ipstenu/varnish-http-purge/blob/b35efddb6924af5f03b00fcf6f8f4f5c91f65520/style.css. Note that it was previously `#F56E28`.

It's quite distracting. What's the reason for loading an additional stylesheet just to make the item green?

<img width="721" alt="green" src="https://user-images.githubusercontent.com/617637/40234411-0a6a51bc-5aa7-11e8-8210-656c26d79a5d.png">

**Comment by Ipstenu** [comment]
Around 10-20 tickets a week (yes) from people who can't find the button.

**Comment by Ipstenu** [comment]
I'm going to roll back the green to something less jarring and more 'in line' with everything else on the bar (currently leaning towards the carrot icon but suggestions welcome)

See https://github.com/Ipstenu/varnish-http-purge/tree/REL_4.5.1

**Comment by porcospino** [comment]
U+1F92E, perhaps?

**Comment by Ipstenu** [comment]
Given how WP works, I was looking at the Dashicons 🤣 

https://developer.wordpress.org/resource/dashicons/#smiley lacks that punch. And there's no toilet (for the old Varnish Flush joke)
