### ISSUE TITLE
Custom CSS

### ISSUE THREAD

**Issue by amitmalewar** [Ipstenu/varnish-http-purge#53]
`<link rel='stylesheet' id='varnish_http_purge-css'  href='/wp-content/plugins/varnish-http-purge/style.css?ver=4.5.2' type='text/css' media='all' />`

This should load only if the user is logged in.

**Comment by Ipstenu** [comment]
Will be fixed in 4.6

**Comment by amitmalewar** [comment]
Thank you @Ipstenu
