### ISSUE TITLE
"The "Age" header is set to an invalid time, which will result in incorrect caching."

### ISSUE THREAD

**Issue by ivanovalex02** [Ipstenu/varnish-http-purge#73]
https://github.com/Ipstenu/varnish-http-purge/blob/3b00c5aadb6f4a20877311a7f3c256b2cfbebcfd/debug.php#L594

Any ideas why do we need strtotime here?

**Comment by Ipstenu** [comment]
Because strtotime can be used to determine if the time is a valid time (and not say February 30, 2018).

What's the actual problem you're having?

**Comment by Ipstenu** [comment]
Assuming this issue is due to incorrect server configurations. Please feel free to leave more information, but without knowing what the problem is (beyond the debugger telling you that your age headers are broken) there's nothing to fix here.
