### ISSUE TITLE
Purging all at customize_save_after

### ISSUE THREAD

**Issue by soderlind** [Ipstenu/varnish-http-purge#85]
Would it be stupid to do a `varnish_http_purge_events_full` on the `customize_save_after` event ?

**Comment by Ipstenu** [comment]
That's what gets triggered after you use customizer to save things? That sounds reasonable. It might thrash a little if you were changing a lot, but  that wouldn't be a constant thing. Heck, that should probably go in the core plugin.

**Comment by soderlind** [comment]
My thought also, that it should be in core :) 

Anyway, thank you for your quick answer, for now I'll add it using `varnish_http_purge_events` and `varnish_http_purge_events_full`
