### ISSUE TITLE
Multiple IP functionality not working.

### ISSUE THREAD

**Issue by Muhammad-Zaka** [Ipstenu/varnish-http-purge#89]
We have multiple varnish backend servers and using the plugin to send purge request to all of the varnish servers.
The issue is when i add 1 ip it works fawlessly but when added multiple IP's with the convention suggested it stops sending request to any backend.

**Comment by Ipstenu** [comment]
Thanks for letting me know. I'll dig into this and see if I can reproduce the issue... You're separting with a comma, right?

**Comment by Muhammad-Zaka** [comment]
Yes, I am separating the servers with comma.
It works just fine when i pass one IP.

**Comment by Muhammad-Zaka** [comment]
The text field automatically adds a space after the comma.

**Comment by Ipstenu** [comment]
Okay I think I know why. I made a 5.0.1 branch - https://github.com/Ipstenu/varnish-http-purge/tree/REL_5.0.1 - if you want to test it.

**Comment by Muhammad-Zaka** [comment]
Tested the branch 5.0.1. This time only the 1st IP is receiving purge request. The other IP's don't get any request.
Attaching the screenshot of the plugin settings and varnish log on cache clear.


![Screenshot_3](https://user-images.githubusercontent.com/48753375/115840040-b3feb180-a434-11eb-9bfc-468fcbe34115.png)

![Screenshot_4](https://user-images.githubusercontent.com/48753375/115841028-caf1d380-a435-11eb-99a8-51f2aa0932b8.png)

**Comment by Ipstenu** [comment]
> The text field automatically adds a space after the comma.

Fyi that should be fine.

I'm going to see if I can figure out why it's not looping!

**Comment by Muhammad-Zaka** [comment]
The latest changes seems to have fixed the issue. I tested the site now its sending purge request to every IP.

![working](https://user-images.githubusercontent.com/48753375/116066343-cea37700-a63c-11eb-859c-6f7dadcbffc3.png)

**Comment by Ipstenu** [comment]
WHEW! Okay, I'll get that rollin for everyone this week.

**Comment by Muhammad-Zaka** [comment]
Sounds good. That would be great.

**Comment by Muhammad-Zaka** [comment]
Thanks for the fix :)
