### ISSUE TITLE
Varnish 4 and RegExp Purge

### ISSUE THREAD

**Issue by miscs** [Ipstenu/varnish-http-purge#92]
Hi Mika,

I am testing wordpress with varnish 4, purging works but not purge all.
I see an PURGE /.* in varnishncsa log (status 200) but pages are still old after this request has been send.

I´ve read that varnish 4 does not support regexp purging and BAN should be used instead. Might that be the problem? 

In old issues I found a link to https://github.com/aaemnnosttv/varnish-vcl-collection/blob/5830257b956be56224f6ac676a7bd58b04ab7593/lib/purge.vcl but do I really need to include all these purge functions to make it work with varnish 4?

Thanks for any pointers!
Steve

**Comment by Ipstenu** [comment]
> I see an PURGE /.* in varnishncsa log (status 200) but pages are still old after this request has been send.

If you see that, then the issue is with your VCLs and not the plug-in. You probably do need all the purge functions. Sadly I’m on Varnish 6 and the formatting is different, but it mostly looks like this

https://github.com/Ipstenu/varnish-http-purge/wiki/purge.vcl
